### PR TITLE
Using Composer

### PR DESCRIPTION
**Pull request by joel-depiltech**
Hello,
I made a big change about how to include PHPMailer library and use this library. I really love Composer and I found it so useful 
So I create a composer file to include PHPMailer as a vendor and directly as this library to third_party folder.
PLEASE NO ACCEPT THIS PR. I just create it to discuss with you and if you are agree with this installation mode.
So what do you think about ?

Regards,
Joël

### CODE REVIEW

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/starter-public-edition-4/blob/v4.3.25/platform/composer.json#L30

Yes, for my projects I also use Composer about adding PHPMailer. This is easy.
But for MY_Email.php and MY_email_helper.php things become tricky.

I am in the mood this project to stay as it is, in this old-fashioned file placement style. Thus it is easy upgrading the Email library for legacy sites that still don't use Composer, starting with CodeIgniter 2, no one is excluded.

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/starter-public-edition-4/commit/688aa1a3b1d3c42d681e513710bee98749a3f278

Adding a section within README.md on how to install PHPMailer 5.2 by using Composer seems to me appropriate. At least it is something I can do.

**Comment by joel-depiltech** [comment]
For files MY_Email.php and MY_email_helper.php there will be automatically include because all this project will be in third_party. For this developers just need to add this project as a package, like this : `$this->load->add_package_path(APPPATH.'third_party/phpmailer');` You can read more here : https://www.codeigniter.com/user_guide/libraries/loader.html

Yes you can add a section to README.md and invite people to install this project through Composer. Don't forget to write about to activate composer autoload in the file /application/config/config.php

Thanks to your interest for my work.

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/codeigniter-phpmailer/commit/8ff2d4a6f7dff7b85908a979ff918e5866177045 - instructions for installing PHPMailer through Composer.

About CodeIgniter's packager (I've forgotten its name, spark?) - no. Nobody supports it, I don't intend to do so too.

The feature
```
$this->load->add_package_path('...');
```
is something I simply don't like, sorry.

**Comment by ivantcholakov** [comment]
@joel-depiltech

Is what I did here good enough?

**Comment by joel-depiltech** [comment]
@ivantcholakov yes you did right but this project no need its own composer.json file in this case.

This is how I would see it:

1. Enable composer on the computer
2. Configure CI instance config variable to include composer autoload 
3. Install this project by taping `composer require composer/phpmailer`
4. Autoload this package by adding `APPPATH.'third_party/phpmailer'` in the `$autoload['packages']` array in the file /application/config/autoload.php

Before this you just need to submit your project to packagist.org

**Comment by ivantcholakov** [comment]
@ivantcholakov

But this would exclude CodeIgniter 2 users.

What you suggest might happen in the future. When the moment comes (don't know yet), I think to migrate this library for use PHPMailer 6 and to drop support for CodeIgniter 2 simultaneously. Then I will revisit this topic, which I am going to keep open.

Meanwhile I will make a release of the currently made instructions, they are a partial improvement, at least.

**Comment by joel-depiltech** [comment]
Thanks you so much to merge my modifications. 

Yes you are right about CI 2 users.
Maybe I can help you to move to PHPMailer 6

Regards

**Comment by ivantcholakov** [comment]
I am going to try to prepare a Composer package soon.

**Comment by ivantcholakov** [comment]
Done, thank you for your suggestion. See https://github.com/ivantcholakov/codeigniter-phpmailer/releases/tag/v1.4.4

**Pull request closed without merging**
